name: Static Analysis

# Run on main push and pull requests
on:
  push:
  pull_request:

jobs:

  check-for-duplicates:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
          should_skip: ${{ steps.skip_check.outputs.should_skip }}
      steps:
        - id: skip_check
          uses: fkirc/skip-duplicate-actions@master
          with:
            concurrent_skipping: 'same_content'
            skip_after_successful_duplicate: 'true'
            do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
              
  cpp-check:    
    name: Run cppcheck
    needs: check-for-duplicates
    runs-on: ubuntu-18.04
    timeout-minutes: 15

    steps:

      - name: Install cppcheck
        run: sudo apt-get install cppcheck -y

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run general cppcheck
        run: cppcheck --force --inline-suppr --quiet . 2> cppcheck_err.txt

      - name: Archive Static Analysis Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-err
          path: ./cppcheck_err.txt

      - name: Check for errors
        run: |
          if [[ -s cppcheck_err.txt ]];
          then
            cat cppcheck_err.txt
            exit -1
          fi
